[build]
  publish = "build"
  command = "yarn build"

[functions]
  directory = "netlify/functions"
  node_bundler = "zip-it-and-ship-it"

[[redirects]]
  from = "/functions/*"
  to = "/functions/:splat"
  status = 200